-- CRIAR # CREATE
-- EDITAR # ALTER
-- DELETAR # DROP

-- MODIFICANDO COLUNAS E TABELAS
CREATE TABLE teste (
Id INT AUTO_INCREMENT PRIMARY KEY,
Nome VARCHAR(255)
);

-- Add coluna
ALTER TABLE teste ADD Inteiro INT;
ALTER TABLE teste ADD Idade INT;

-- Modifica coluna
ALTER TABLE teste MODIFY Idade TEXT;
ALTER TABLE teste MODIFY Inteiro INT NOT NULL;

-- Apaga coluna
ALTER TABLE teste DROP Inteiro;

-- Adiciona Foreign Key
CREATE TABLE teste2 (
Id INT AUTO_INCREMENT PRIMARY KEY
);

ALTER TABLE teste ADD FKTESTE INT;
ALTER TABLE teste ADD CONSTRAINT FK_TESTE_TESTE2 FOREIGN KEY (FKTESTE) REFERENCES teste2(id);

-- Apagar tabela com FK
ALTER TABLE teste DROP FOREIGN KEY FK_TESTE_TESTE2;
DROP TABLE teste2;
ALTER TABLE teste DROP FKTESTE;

DROP TABLE teste;

SELECT * FROM escola_db.teste;