-- Alergia
INSERT INTO Alergia (idAlergia, Nome)
VALUES (1, 'Glúten');

-- GERADO POR IA ##############################################################################################################################

INSERT INTO Alergia (Nome)
VALUES
('Avelã'),
('Feijão'),
('Canela'),
('Sulfitos'),
('BHT'),
('Açúcar'),
('Picadas de Insetos'),
('Picadas de Insetos'),
('Prata'),
('Café'),
('Ácido Acetilsalicílico'),
('Bário'),
('Sulfitos'),
('BHA'),
('Berílio'),
('Corantes'),
('Mercúrio'),
('Aspartame'),
('Coco'),
('Carne de Porco'),
('Níquel'),
('Medicamentos'),
('Arsênio'),
('Propilenoglicol'),
('Gelatina'),
('Glutamato Monossódico'),
('Propilenoglicol'),
('Selênio'),
('Propilenoglicol'),
('Gelatina'),
('Arsênio'),
('Banana'),
('Soja'),
('Canela'),
('Conservantes'),
('Medicamentos'),
('Carne de Porco'),
('Glúten'),
('Frutos do Mar'),
('Pelos de Animais'),
('Medicamentos'),
('Aspartame'),
('Moluscos'),
('Arsênio'),
('Castanhas'),
('Chocolate'),
('Morango'),
('Lactose'),
('Propilenoglicol'),
('Canela'),
('Mel'),
('Sulfato'),
('Urânio'),
('Selênio'),
('Abacaxi'),
('Cobalto'),
('Fragrâncias'),
('Feijão'),
('Corantes'),
('Poeira'),
('Banana'),
('Ácido Salicílico'),
('Cebola'),
('Conservantes'),
('Açúcar'),
('Abacaxi'),
('Latex'),
('Dipirona'),
('Conservantes'),
('Soja'),
('Amendoim'),
('Estrôncio'),
('Ovos'),
('Césio'),
('Carne Vermelha'),
('Cebola'),
('Mel'),
('Avelã'),
('Latex'),
('Sacarina'),
('Ibuprofeno'),
('Mel'),
('Trigo'),
('Alho'),
('Avelã'),
('Bário'),
('Pólen'),
('Formol'),
('Sulfitos'),
('Tomate'),
('Canela'),
('Álcool'),
('Castanhas'),
('Fragrâncias'),
('Prata'),
('Sacarina'),
('Álcool'),
('Tálio'),
('Abacaxi');

