-- Disciplina
INSERT INTO Disciplina (id, Nome)
VALUES (1, 'Matemática');

-- GERADO POR IA ##############################################################################################################################

INSERT INTO Disciplina (Nome)
VALUES
('Inglês'),
('Marketing'),
('Trigonometria'),
('Trigonometria'),
('Contabilidade'),
('Ciência de Dados'),
('Publicidade'),
('Ecologia'),
('Ciência da Computação'),
('Filosofia'),
('Engenharia Civil'),
('Engenharia de Software'),
('Ciência da Computação'),
('Engenharia de Materiais'),
('História'),
('Genética'),
('Planejamento Estratégico'),
('Robótica'),
('Algoritmos'),
('Teatro'),
('Redação'),
('Engenharia de Computação'),
('Algoritmos'),
('Gestão de Pessoas'),
('Economia'),
('Ciências'),
('Geopolítica'),
('Tecnologia'),
('Tecnologia'),
('História da Ciência'),
('História da Música'),
('Antropologia'),
('Gestão de Pessoas'),
('Fotografia'),
('Algoritmos'),
('Engenharia Química'),
('Antropologia'),
('Ciências'),
('Finanças'),
('Publicidade'),
('Fotografia'),
('Geologia'),
('Planejamento Estratégico'),
('Espanhol'),
('História da Ciência'),
('Tecnologia'),
('Fisioterapia'),
('História do Brasil'),
('Robótica'),
('Enfermagem'),
('Geometria'),
('Criptografia'),
('Geologia'),
('Contabilidade'),
('Estatística'),
('Tecnologia'),
('Planejamento Estratégico'),
('Teoria dos Números'),
('Algoritmos'),
('Geologia'),
('Engenharia Química'),
('Geologia'),
('Teatro'),
('Medicina'),
('Zoologia'),
('Oceanografia'),
('Engenharia Elétrica'),
('Redação'),
('Engenharia Ambiental'),
('Planejamento Estratégico'),
('Química'),
('Administração'),
('Topologia'),
('Fotografia'),
('Design Gráfico'),
('Botânica'),
('Geopolítica'),
('História do Brasil'),
('Nutrição'),
('Teatro'),
('Economia'),
('Antropologia'),
('Trigonometria'),
('Educação Física'),
('Química'),
('Gestão de Pessoas'),
('Espanhol'),
('Oceanografia'),
('Meteorologia'),
('Fotografia'),
('Meteorologia'),
('Literatura'),
('Álgebra'),
('Finanças'),
('Zoologia'),
('Ciência de Dados'),
('História da Música'),
('Engenharia de Software'),
('História da Arte');